srt {                
    worker_threads  1;
    worker_connections 300 ;
		
    log_file logs/error.log ; 
    log_level info;
         
    server {
        listen 8080; 
        latency 150; #ms

        domain_player pull;
        domain_publisher push;
        backlog 100; #accept connections at the same time
        idle_streams_timeout 10;#s -1: unlimited
        app {
            app_player live ;           
            app_publisher live ; 
            
            record_hls off;#on, off 
            record_hls_segment_duration 10; #unit s
        }
    }
}
